name: Groovy Selenium CI/CD

on:
  workflow_dispatch:   # Manual trigger
    inputs:
      browser:
        description: "Browser to run tests on"
        required: true
        default: "chrome"
      env:
        description: "Environment to run tests (e.g. SIT, UAT, PROD)"
        required: true
        default: "PROD"

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Run Selenium tests
        run: ./gradlew clean test -Penv=${{ github.event.inputs.environment }} -Pbrowser=${{ github.event.inputs.browser }}

      - name: Upload Test Report
        if: always()   # Upload report even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test